gtf_file = 'tests/data/gtf_chr17.gtf'
gtf_file_multi = 'tests/data/test_multi.gtf'
gtf_file_with_chr = 'tests/data/test_with_chr.gtf'
fasta_file = 'tests/data/hg19.nochr.chr17.fa'
vcf_file = 'tests/data/test.vcf.gz'
exon_file = 'tests/data/test_exons.csv'
junction_file = 'tests/data/test_junction.csv'
junction_psi5_file = 'tests/data/test_junction_psi5_file.csv'
junction_psi3_file = 'tests/data/test_junction_psi3_file.csv'
junc_file = 'tests/data/test_junc.csv'

tpm_file = 'tests/data/test_tpm.csv'
count_table_file = 'tests/data/test_count_chr17.csv'

ref_table5_kn = 'tests/data/test_ref_table5_kn.csv.gz'
ref_table3_kn = 'tests/data/test_ref_table3_kn.csv.gz'
