gtf_file = 'tests/data/test.gtf'
fasta_file = 'tests/data/hg19.nochr.chr17.fa'
vcf_file = 'tests/data/test.vcf.gz'
exon_file = 'tests/data/test_exons.csv'
junction_file = 'tests/data/test_junction.csv'
junction_psi5_file = 'tests/data/test_junction_psi5_file.csv'
junction_psi3_file = 'tests/data/test_junction_psi3_file.csv'
junc_file = 'tests/data/test_junc.csv'
